In [1]:
# importing the necessary libraries
import selenium 
import time
# Importing required Exceptions which needs to handled
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException

PATH = "C:\Program Files (x86)\chromedriver.exe"
from selenium import webdriver 

# Activating the chrome browser
driver = webdriver.Chrome(PATH)

# Opening the homepage of OYO 
driver.get("https://www.oyorooms.com/")

In [2]:
# scraping data for noida city 
search_bar = driver.find_element_by_xpath('/html/body/div[2]/div/div[3]/div[1]/div[3]/div/div/div/div[1]/div/div/form/input')
search_bar.send_keys('Noida')
time.sleep(3)

#clicking on noida from drop down list 
noida_btn = driver.find_element_by_xpath('/html/body/div[2]/div/div[3]/div[1]/div[3]/div/div/div/div[1]/div/span/div/div/div[1]/div/div[2]')
noida_btn.click()
time.sleep(2)

In [3]:
# clicking on search button 
search_btn = driver.find_element_by_xpath('/html/body/div[2]/div/div[3]/div[1]/div[3]/div/div[1]/div/div[4]/button')
search_btn.click()

In [6]:
# collecting urls 
urls = []
# clicking on load more button(found 20 more results button)
for i in range(0,3):
    driver.find_element_by_xpath('//span[@class="loadMoreIcon"]').click()
try:    
    for i in driver.find_elements_by_xpath('//a[@class="c-nn640c u-width100"]'):
        urls.append(i.get_attribute('href'))
except:
    pass

In [9]:
#scraping the titles
titles = []
try:
    for i in driver.find_elements_by_xpath('//a[@class="c-nn640c u-width100"]/h3'):
        titles.append(i.text)
except:
    titles.append('No Title')
                  

#scraping the locations of rooms
location = []
try:
    for i in driver.find_elements_by_xpath('//span[@class="u-line--clamp-2"]'):
        location.append(i.text)
except:
    location.append('No location')
                  
                  
#scraping the price of rooms 
price = []
try:  
    for i in driver.find_elements_by_xpath('//span[@class="listingPrice__finalPrice"]'):
        price.append(i.text)
except:
    price.append('No price')   
                  
#scraping the discount of rooms 
discount = []
try:
    for i in driver.find_elements_by_xpath('//span[@class="listingPrice__percentage"]'):
        discount.append(i.text)
except :
       discount.append('No discount')

In [10]:
print(len(titles),len(location),len(price),len(discount))

140 140 140 140

In [11]:
import pandas as pd 
df = pd.DataFrame({'Titles':titles,'Location':location,'Price':price,'Discount':discount})
df

,Titles,Location,Price,Discount
0,OYO 29022 Golden Imperial,"Near Block C, Beta I, Noida",₹999,74% off
1,Capital O 45709 Peaceful Stays,"Near Sec 59 Metro Station, Sector-71, Noida",₹899,71% off
2,OYO 10666 Hotel Star,"Near Nirula,s Hotel, Naya Bans, Noida",₹999,72% off
3,OYO 82414 Hotel Basera,"India, Noida",₹899,48% off
4,OYO 77125 S R Plaza,"Gautam Buddha Nagar, Noida",₹999,70% off
...,...,...,...,...
135,OYO 82128 Golden Regency,"India, Noida",₹899,43% off
136,Capital O 75273 Hotel Exotica Noida Expressway,"Near Sector 105, Noida",₹1249,57% off
137,OYO 9192 Hotel Raghav Residency,"Near Fortune Park, Sector 105, Noida",₹999,44% off
138,OYO Flagship 402 Hotel Noida Residency,"Near Noida City Centre Metro Station, Sector 3...",₹1309,47% off
139,OYO NOD1223 Cross Town Hotel & Restaurants,"Plot no 188, Achheja, Near Hero motors, Dadri ...",₹1049,61% off

In [12]:
df.to_csv(r'C:\\Users\\user\\Downloads\\Extracted_data.csv', index=False)